apiVersion : apps/v1
kind : Deployment
metadata :
  name : appointment-microservice-deployment
spec :
  selector :
    matchLabels :
      app : appointment-microservice-selector
  replicas : 1
  template :
    metadata :
      labels :
        app : appointment-microservice-selector
    spec :
      containers :
        - name : appointment-microservice-container-v2
          image : dipankarduttastl/appointment-microservice-img-v2
          ports :
            - containerPort : 8003
              protocol : TCP
          env :
            - name : DB_HOST
              value : mysql
            - name : DB_NAME
              value : appointmentdb
            - name : DB_USERNAME
              value : dip@dutta
            - name : DB_PASSWORD
              value : dip@dutta
  